include macros.lib
 
.MODEL SMALL

.STACK 64

.DATA
    LN  DB 0AH,0DH,'$'
    C2  DB 'HOLA','$'   
    L1  DB 'ENCONTRO','$'     ;SCASB
    L2  DB 'NO ENCONTRO','$'  ;SCASW
.CODE

MAIN PROC FAR
    MOV AX, @DATA    
    MOV DS,AX  
    
    ;SCASB   ;ESCANEA UNA CADENA BYTE
    ;SCASW   ;ESCANEA UNA CADENA WORD
    ;CLD     ;LIMPIA LA BANDERA DE DIRECCI?N IZQ->DER
    ;REPE    ;REPITE MIENTRAS SEAN EQUALS
    ;REPNE   ;REPITE MENTRAS NO SEAN EQUALS
    
    CLD
    MOV AL,41H
    MOV CX,4
    MOV SI,OFFSET C2
    REPE SCASB
    CMP CX,0
    JB ENCONTRO
    WRITE L2
    JMP FIN
    
    ENCONTRO:
    WRITE L1
    
    FIN:
    .EXIT
MAIN ENDP

READ PROC
    MOV AH,01H
    INT 21H
    RET
READ ENDP

END MAIN