INCLUDE MACROS.LIB


READ_CC MACRO ARRE,CA_LE
    LOCAL CICLO
    MOV SI, 0
    CICLO:
    MOV AH,01H
    INT 21H
    MOV ARRE[SI],AL
    INC SI
    CMP AL,0DH
    JNE CICLO
    MOV CA_LE, SI
ENDM

.286
.MODEL SMALL ;DECLARACION DEL MODELO DE MEMORIA
.STACK 64
.DATA
    CADENA1 DB 10 DUP (?),'$'
    CADENA2 DB 5  DUP (?),'$' 
    C2LENGTH DW (?),'$'
    C1LENGTH DW (?),'$'
    
    LET0 DB 'INGRESA CADENA 1: $'
    LET1 DB 'INGRESA CADENA 2: $'
    LET2 DB 'ENCONTRADO $'
    LET3 DB 'NO ENCONTRADO $'
    
    LN DB 0AH,0DH,'$'
    .CODE
MAIN PROC FAR
    MOV AX, @DATA  
    MOV DS,AX
    MOV ES,AX
    
    WRITE LET0
    READ_CC CADENA1, C1LENGTH
    
    WRITE LET1
    READ_CC CADENA2, C2LENGTH
    WRITE LN
    
    WRITE CADENA1
    WRITE C1LENGTH
    WRITE LN
    WRITE CADENA2
    WRITE C2LENGTH
    WRITE LN
    
    
    
    
FIN:
.EXIT
        
MAIN ENDP
END MAIN