INCLUDE MACROS.LIB
.286
.MODEL SMALL ;DECLARACION DEL MODELO DE MEMORIA
.STACK 64
.DATA
    LET1 DB 'INGRESA UN CARACTER: $',0AH,0DH
    LET2 DB 0AH,0DH, 'ENCONTRADO $'
    LET3 DB 0AH,0DH,'NO ENCONTRADO $'
    LET4 DB "CONCIDENCIA EN: ",'$'
    CARAC DB ?, '$'
    CADENA DB "HOLAEIOU", '$'  
    TAM EQU $ -CADENA
    LN DB 0AH,0DH,'$'
    POS DW ?, '$'
    .CODE
MAIN PROC FAR
    MOV AX, @DATA  
    MOV DS,AX
    MOV ES,AX ; --
    WRITE CADENA
    WRITE LN
    WRITE LET1
    CALL READ
    MOV CARAC,AL
    CLD
    MOV SI,0
    MOV CX, TAM
    MOV AL, CARAC
    LEA DI,CADENA
    REPNE SCASB
    JE ENCONTRO
    JMP NOENC
    ENCONTRO:
    WRITE LET2
    WRITE LN
    WRITE LET4
    ADD DI,30H
    SUB DI,8
    MOV POS,DI
    WRITE POS
    
    JMP FIN
NOENC:
    WRITE LET3
    
FIN:
.EXIT
        
MAIN ENDP
READ PROC
   MOV AH,01H
   INT 21H
   RET
READ ENDP
END MAIN
